# Generated by Django 5.2.3 on 2025-07-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(help_text='Cédula o Pasaporte del estudiante.', max_length=8, unique=True)),
                ('nationality', models.CharField(choices=[('V', 'Venezolano/a'), ('E', 'Extranjero/a')], help_text="Nacionalidad del estudiante ('V' para Venezolano, 'E' para Extranjero).", max_length=1)),
                ('names', models.CharField(help_text='Nombres del estudiante.', max_length=30)),
                ('lastnames', models.CharField(help_text='Apellidos del estudiante.', max_length=30)),
                ('born_date', models.DateField(help_text='Fecha de nacimiento del estudiante (debe tener más de 5 años).')),
                ('gender', models.CharField(choices=[('Femenine', 'Femenino'), ('Masculine', 'Masculino')], help_text='Género del estudiante.', max_length=10)),
                ('address', models.TextField(help_text='Dirección del estudiante (máximo 300 caracteres).', max_length=300)),
                ('home_phone', models.CharField(blank=True, help_text='Número de teléfono de casa.', max_length=11, null=True)),
                ('cellphone', models.CharField(blank=True, help_text='Número de teléfono celular.', max_length=11, null=True)),
                ('email', models.EmailField(help_text='Correo electrónico del estudiante.', max_length=50)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
