# Generated by Django 5.2.3 on 2025-07-12 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_degree',
            field=models.CharField(help_text='Grado académico.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_institution_address',
            field=models.CharField(help_text='Dirección del Plantel Educativo.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_institution_name',
            field=models.CharField(help_text='Nombre del Plantel Educativo.', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_institution_type',
            field=models.CharField(help_text='Tipo de Plantel (Privado, Mixto, etc.)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='allergies',
            field=models.CharField(help_text='Indique las alergias del estudiante. Dejar en blanco si no tiene o se desconocen.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='housing_condition',
            field=models.CharField(help_text='Estado de la Vivienda (Propia, Alquilada, etc.)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='housing_type',
            field=models.CharField(help_text='Tipo de Vivienda (Casa, Edificio, Apartamento, Quinta, etc.)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_report',
            field=models.CharField(help_text='Indique datos del informe médico del estudiante. Dejar en blanco en caso contrario.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='number_people_living_housing',
            field=models.IntegerField(default=1, help_text='Cantidad de personas que habitan en la Vivienda.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='student',
            name='regular_medical_treatment',
            field=models.CharField(help_text='Indique si el estudiante toma tratamiento médico regular. Dejar en blanco en caso contrario.', max_length=200, null=True),
        ),
    ]
