# Generated by Django 5.2.3 on 2025-07-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_academic_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='allergies',
            field=models.CharField(blank=True, help_text='Indique las alergias del estudiante. Dejar en blanco si no tiene o se desconocen.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_report',
            field=models.CharField(blank=True, help_text='Indique datos del informe médico del estudiante. Dejar en blanco en caso contrario.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='regular_medical_treatment',
            field=models.CharField(blank=True, help_text='Indique si el estudiante toma tratamiento médico regular. Dejar en blanco en caso contrario.', max_length=200, null=True),
        ),
    ]
