# Generated by Django 5.2.3 on 2025-07-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_allergies_alter_student_medical_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_institution_address',
            field=models.TextField(help_text='Dirección del Plantel Educativo.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='allergies',
            field=models.TextField(blank=True, help_text='Indique las alergias del estudiante. Dejar en blanco si no tiene o se desconocen.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_report',
            field=models.TextField(blank=True, help_text='Indique datos del informe médico del estudiante. Dejar en blanco en caso contrario.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='regular_medical_treatment',
            field=models.TextField(blank=True, help_text='Indique si el estudiante toma tratamiento médico regular. Dejar en blanco en caso contrario.', max_length=200, null=True),
        ),
    ]
