# Generated by Django 5.2.3 on 2025-07-14 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_academic_institution_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address_legal_parent',
            field=models.TextField(help_text='Dirección de Habitación (Solo si es diferente a la del Beneficiario).', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='address_relative',
            field=models.TextField(blank=True, help_text='Dirección de Habitación (Solo si es diferente a la del Beneficiario).', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='age_legal_parent',
            field=models.IntegerField(help_text='Edad del representante legal.', null=True, validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AddField(
            model_name='student',
            name='age_relative',
            field=models.IntegerField(help_text='Edad del familiar.', null=True, validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AddField(
            model_name='student',
            name='born_date_legal_parent',
            field=models.DateField(help_text='Fecha de nacimiento del representante legal', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='born_date_relative',
            field=models.DateField(help_text='Fecha de nacimiento del familiar', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cellphone_legal_parent',
            field=models.CharField(help_text='Número de teléfono celular.', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cellphone_relative',
            field=models.CharField(help_text='Número de teléfono celular del familiar.', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='document_id_legal_parent',
            field=models.CharField(help_text='Cédula o Pasaporte del representante legal.', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='document_id_relative',
            field=models.CharField(help_text='Cédula o Pasaporte del familiar.', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email_legal_parent',
            field=models.EmailField(help_text='Correo electrónico del representante legal.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fullname_legal_parent',
            field=models.CharField(help_text='Nombre completo del representante legal.', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fullname_relative',
            field=models.CharField(help_text='Nombre completo del familiar.', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='home_phone_legal_parent',
            field=models.CharField(blank=True, help_text='Número de Habitación (Solo si es diferente a la del Beneficiario).', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='home_phone_relative',
            field=models.CharField(blank=True, help_text='Número de Habitación (Solo si es diferente a la del Beneficiario).', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='job_title_legal_parent',
            field=models.CharField(blank=True, help_text='Cargo del representante legal.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='job_title_relative',
            field=models.CharField(blank=True, help_text='Cargo del familiar.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='marital_status_legal_parent',
            field=models.CharField(choices=[('Single', 'Soltero/a'), ('Married', 'Casado/a'), ('Divorced', 'Divorciado/a'), ('Widowed', 'Viudo/a')], help_text='Estado civil del representante legal.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='marital_status_relative',
            field=models.CharField(choices=[('Single', 'Soltero/a'), ('Married', 'Casado/a'), ('Divorced', 'Divorciado/a'), ('Widowed', 'Viudo/a')], help_text='Estado civil del familiar.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality_id_legal_parent',
            field=models.CharField(choices=[('V', 'Venezolano/a'), ('E', 'Extranjero/a')], help_text='Nacionalidad del representante legal.', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality_id_relative',
            field=models.CharField(choices=[('V', 'Venezolano/a'), ('E', 'Extranjero/a')], help_text='Nacionalidad del familiar.', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='office_phone_legal_parent',
            field=models.CharField(blank=True, help_text='Número de Oficina.', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='office_phone_relative',
            field=models.CharField(blank=True, help_text='Número de Oficina del familiar.', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profession_legal_parent',
            field=models.CharField(help_text='Profesión u oficio del representante legal.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profession_relative',
            field=models.CharField(help_text='Profesión u oficio del familiar.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='relationship_legal_parent',
            field=models.CharField(help_text='Parentesco del representante legal.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='relationship_relative',
            field=models.CharField(help_text='Parentesco del familiar.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='workplace_legal_parent',
            field=models.CharField(help_text='Lugar de trabajo del representante legal.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='workplace_relative',
            field=models.CharField(help_text='Lugar de trabajo del familiar.', max_length=40, null=True),
        ),
    ]
