# Generated by Django 5.2.3 on 2025-07-20 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_address_legal_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Nombre completo del contacto de emergencia.', max_length=100, verbose_name='Nombre completo')),
                ('relationship', models.CharField(help_text='Parentesco del contacto de emergencia.', max_length=50, verbose_name='Parentesco')),
                ('cellphone', models.CharField(help_text='Teléfono del contacto de emergencia.', max_length=11, verbose_name='Teléfono')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='students.student')),
            ],
            options={
                'verbose_name': 'Contacto de Emergencia',
                'verbose_name_plural': 'Contactos de Emergencia',
            },
        ),
    ]
