# Generated by Django 5.2.3 on 2025-07-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_document_id',
            field=models.BooleanField(default=True, help_text='Marque si el estudiante posee cédula o pasaporte.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='document_id',
            field=models.CharField(blank=True, help_text='Cédula o Pasaporte del estudiante.', max_length=8),
        ),
    ]
