# Generated by Django 5.2.3 on 2025-07-21 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_has_document_id_alter_student_document_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRelative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(help_text='Parentesco del representante legal.', max_length=20, null=True)),
                ('fullname', models.CharField(help_text='Nombre completo del representante legal.', max_length=70, null=True)),
                ('born_date', models.DateField(help_text='Fecha de nacimiento del representante legal', null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Soltero/a'), ('Married', 'Casado/a'), ('Divorced', 'Divorciado/a'), ('Widowed', 'Viudo/a')], help_text='Estado civil del representante legal.', max_length=20, null=True)),
                ('document_id', models.CharField(help_text='Cédula o Pasaporte del representante legal.', max_length=8, null=True, unique=True)),
                ('nationality', models.CharField(choices=[('V', 'Venezolano/a'), ('E', 'Extranjero/a')], help_text='Nacionalidad del representante legal.', max_length=1, null=True)),
                ('profession', models.CharField(help_text='Profesión u oficio del representante legal.', max_length=30, null=True)),
                ('address', models.TextField(help_text='Dirección de Habitación (Solo si es diferente a la del Beneficiario).', max_length=300, null=True)),
                ('home_phone', models.CharField(blank=True, help_text='Número de Habitación (Solo si es diferente a la del Beneficiario).', max_length=11, null=True)),
                ('cellphone', models.CharField(help_text='Número de teléfono celular.', max_length=11, null=True)),
                ('email', models.EmailField(help_text='Correo electrónico del representante legal.', max_length=50, null=True)),
                ('workplace', models.CharField(help_text='Lugar de trabajo del representante legal.', max_length=40, null=True)),
                ('job_title', models.CharField(blank=True, help_text='Cargo del representante legal.', max_length=30, null=True)),
                ('office_phone', models.CharField(blank=True, help_text='Número de Oficina.', max_length=11, null=True)),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Familiares',
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='address_legal_parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address_relative',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age_legal_parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age_relative',
        ),
        migrations.RemoveField(
            model_name='student',
            name='born_date_legal_parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='born_date_relative',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cellphone_legal_parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cellphone_relative',
        ),
        migrations.RemoveField(
            model_name='student',
            name='document_id_legal_parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='document_id_relative',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email_legal_parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fullname_legal_parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fullname_relative',
        ),
        migrations.RemoveField(
            model_name='student',
            name='home_phone_legal_parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='home_phone_relative',
        ),
        migrations.RemoveField(
            model_name='student',
            name='job_title_legal_parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='job_title_relative',
        ),
        migrations.RemoveField(
            model_name='student',
            name='marital_status_legal_parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='marital_status_relative',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nationality_id_legal_parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nationality_id_relative',
        ),
        migrations.RemoveField(
            model_name='student',
            name='office_phone_legal_parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='office_phone_relative',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profession_legal_parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profession_relative',
        ),
        migrations.RemoveField(
            model_name='student',
            name='relationship_legal_parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='relationship_relative',
        ),
        migrations.RemoveField(
            model_name='student',
            name='workplace_legal_parent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='workplace_relative',
        ),
        migrations.AddField(
            model_name='student',
            name='id_legal_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_legal_parent', to='students.studentrelative'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_relative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_relative', to='students.studentrelative'),
        ),
    ]
