# Generated by Django 5.2.3 on 2025-07-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentrelative_remove_student_address_legal_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrelative',
            name='document_id',
            field=models.CharField(help_text='Cédula o Pasaporte del representante legal.', max_length=8, null=True),
        ),
    ]
