# Generated by Django 5.2.3 on 2025-07-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_studentrelative_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrelative',
            name='address',
            field=models.TextField(blank=True, help_text='Dirección de Habitación (Solo si es diferente a la del Beneficiario).', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='studentrelative',
            name='workplace',
            field=models.CharField(blank=True, help_text='Lugar de trabajo del representante legal.', max_length=40, null=True),
        ),
    ]
