# Generated by Django 5.2.3 on 2025-07-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='code',
        ),
        migrations.AddField(
            model_name='instrument',
            name='category',
            field=models.CharField(choices=[('Wind', 'Viento'), ('String', 'Cuerdas'), ('Percussion', 'Percusión'), ('Other', 'Otros')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
