# Generated by Django 5.2.3 on 2025-07-15 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_period', '0001_initial'),
        ('instruments', '0001_initial'),
        ('orchestral_projects', '0001_initial'),
        ('students', '0005_student_address_legal_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailAcademicInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_date', models.DateField()),
                ('type', models.CharField(choices=[('New admission', 'Nuevo ingreso'), ('Re-entry', 'Reingreso'), ('Data update', 'Actualización de datos'), ('Re-enrollment', 'Reinscripción regular')], max_length=30)),
                ('id_academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_period.academicperiod')),
                ('id_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
                ('id_orchestral_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestral_projects.orchestralproject')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'Detalle de Inscripción Académica',
                'verbose_name_plural': 'Detalles de Inscripción Académica',
                'ordering': ['-inscription_date'],
                'unique_together': {('id_student', 'id_academic_period')},
            },
        ),
    ]
