# Generated by Django 5.2.3 on 2025-07-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_period', '0002_detailacademicinscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicperiod',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
