# Generated by Django 5.2.3 on 2025-07-30 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_period', '0003_academicperiod_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailacademicinscription',
            options={'ordering': ['id_academic_period'], 'verbose_name': 'Detalle de Inscripción Académica', 'verbose_name_plural': 'Detalles de Inscripción Académica'},
        ),
    ]
